# yaml for auto reconstructions of multiple colmap models. This config defines which folders a colmap reconstruction should run on

# colmap project.ini file that should be used for all reconstructions (nr of features, cam calib etc.)
# project_ini: "~/transfer/eval/spring-cloudy/tiny-floor1/project.ini"
reconstruction_quality: low # quality settings {low, medium, high, extreme}

# workspace folder a reconstruction should be run on
workspaces:
  x1:
    ws_path: "/home/azuo/transfer/eval/spring-cloudy/tiny-floor1/sp1" # path to the root level workspace folder (should contain "images" subfolder)
  x2:
    ws_path: "~/transfer/eval/spring-cloudy/tiny-floor1/sparse2x"
  x3:
    ws_path: "~/transfer/eval/spring-cloudy/tiny-floor1/sparse3x"
  x5:
    ws_path: "~/transfer/eval/spring-cloudy/tiny-floor1/sparse5x"
