# yaml for auto reconstructions of multiple colmap models. This config defines which folders a colmap reconstruction should run on

reconstruction_quality: low # quality settings {low, medium, high, extreme}

# workspace folder a reconstruction should be run on. each workspace should contain a subfolder "images" with the images to be reconstructed.
workspaces:
  x5:
    ws_path: "~/transfer/eval/spring-cloudy/tiny-floor1/sparse5x"
  x3:
    ws_path: "~/transfer/eval/spring-cloudy/tiny-floor1/sparse3x"
  x2:
    ws_path: "~/transfer/eval/spring-cloudy/tiny-floor1/sparse2x"
